"""Type stubs for the native module (see documentation/python-api.md)."""

import datetime
import os
from types import TracebackType
from typing import Any, Dict, List, Optional, Sequence, Type, Union

__version__: str

Path = Union[str, "os.PathLike[str]"]
AttrPath = Union[str, Sequence[str]]
# None, bool, int, float, str, bytes, list, dict, date, datetime
Value = Any
CommitResult = Dict[str, Any]

class Error(Exception): ...
class ConflictError(Error): ...
class ConstraintError(Error): ...
class NotFoundError(Error): ...
class InvalidError(Error): ...
class ReadOnlyError(Error): ...
class LockedError(Error): ...
class IoError(Error): ...
class CorruptError(Error): ...
class TimeoutError(Error): ...
class ClosedError(Error): ...
class InternalError(Error): ...

class Store:
    @staticmethod
    def open(
        path: Path,
        *,
        create_if_missing: bool = True,
        fsync: str = "always",
        group_max_delay: float = 0.01,
        group_max_batch: int = 64,
        segment_size: int = 64 << 20,
        checkpoint_wal_size: Optional[int] = 256 << 20,
        checkpoint_interval: Optional[float] = 300.0,
        checkpoint_on_close: bool = True,
        checkpoint_keep: int = 2,
        checkpoint_background: bool = True,
        archive: Optional[Path] = None,
    ) -> "Store": ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __enter__(self) -> "Store": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]] = None,
        exc: Optional[BaseException] = None,
        traceback: Optional[TracebackType] = None,
    ) -> bool: ...
    def transaction(self, *, idempotency_key: Optional[str] = None) -> "Transaction": ...
    def node(
        self, id: str, *, min_seq: Optional[int] = None, timeout: Optional[float] = None
    ) -> Optional[Dict[str, Any]]: ...
    def edge(
        self, id: int, *, min_seq: Optional[int] = None, timeout: Optional[float] = None
    ) -> Optional[Dict[str, Any]]: ...
    def wait_for_seq(self, seq: int, *, timeout: Optional[float] = None) -> int: ...
    def seq(self) -> int: ...
    def synced_seq(self) -> Optional[int]: ...
    def read_only(self) -> Optional[str]: ...
    def history(self) -> str: ...
    def status(self) -> Dict[str, Any]: ...
    def catalog(self, *, min_seq: Optional[int] = None, timeout: Optional[float] = None) -> Dict[str, Any]: ...
    def create_index(self, path: AttrPath, *, idempotency_key: Optional[str] = None) -> CommitResult: ...
    def drop_index(self, path: AttrPath, *, idempotency_key: Optional[str] = None) -> CommitResult: ...
    def add_constraint(
        self, kind: str, label: str, path: AttrPath, *, idempotency_key: Optional[str] = None
    ) -> CommitResult: ...
    def drop_constraint(
        self, kind: str, label: str, path: AttrPath, *, idempotency_key: Optional[str] = None
    ) -> CommitResult: ...
    def sync(self) -> None: ...
    def checkpoint(self) -> Dict[str, Any]: ...
    def backup(self, dest: Path) -> Dict[str, Any]: ...

class Transaction:
    def upsert_node(
        self,
        id: str,
        *,
        labels: Sequence[str] = (),
        attr: Optional[Dict[str, Value]] = None,
        meta: Optional[Dict[str, Value]] = None,
        expected_version: Optional[int] = None,
    ) -> None: ...
    def delete_node(self, id: str, *, expected_version: Optional[int] = None) -> None: ...
    def add_edge(
        self,
        from_: str,
        to: str,
        *,
        type: Optional[str] = None,
        attr: Optional[Dict[str, Value]] = None,
        meta: Optional[Dict[str, Value]] = None,
    ) -> int: ...
    def upsert_edge(
        self,
        *,
        id: Optional[int] = None,
        from_: Optional[str] = None,
        to: Optional[str] = None,
        type: Optional[str] = None,
        attr: Optional[Dict[str, Value]] = None,
        meta: Optional[Dict[str, Value]] = None,
        expected_version: Optional[int] = None,
    ) -> int: ...
    def delete_edge(self, id: int, *, expected_version: Optional[int] = None) -> None: ...
    def set_attr(
        self, target: Union[str, int], key: str, value: Value, *, expected_version: Optional[int] = None
    ) -> None: ...
    def remove_attr(self, target: Union[str, int], key: str, *, expected_version: Optional[int] = None) -> None: ...
    def append_attr(
        self, target: Union[str, int], key: str, value: Value, *, expected_version: Optional[int] = None
    ) -> None: ...
    def add_label(self, id: str, label: str, *, expected_version: Optional[int] = None) -> None: ...
    def remove_label(self, id: str, label: str, *, expected_version: Optional[int] = None) -> None: ...
    def set_edge_type(self, id: int, type: Optional[str], *, expected_version: Optional[int] = None) -> None: ...
    def commit(self) -> CommitResult: ...
    @property
    def result(self) -> Optional[CommitResult]: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> "Transaction": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]] = None,
        exc: Optional[BaseException] = None,
        traceback: Optional[TracebackType] = None,
    ) -> bool: ...

def verify(path: Path) -> Dict[str, Any]: ...
def restore(
    dest: Path,
    *,
    backup: Optional[Path] = None,
    archive: Optional[Path] = None,
    seq: Optional[int] = None,
    time: Optional[datetime.datetime] = None,
) -> Dict[str, Any]: ...
