// Builds the console's generated design-system files (step 16a):
//   design-system/tokens.css  from design-system/tokens.json
//   design-system/bundle.js   from design-system/src/index.jsx (esbuild, as the design system builds it)
// `--check` builds into memory and fails if a committed file is out of date (CI).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ds = join(root, 'design-system');
const check = process.argv.includes('--check');

/** tokens.json (the design system's list shape) -> CSS custom properties, light and dark. */
export function tokensCss(t) {
  const out = ['/* IronWeaver::DB tokens. Generated by tools/build.mjs from tokens.json: do not edit. */'];
  const [first, ...others] = t.color.themes.map((x) => x.id);
  const colorOf = (tok, theme) => (typeof tok.value === 'string' ? tok.value : tok.value[theme] ?? tok.value[first]);
  const block = (sel, theme) => {
    out.push(`${sel} {`);
    for (const tok of t.color.tokens) out.push(`  --${tok.name}: ${colorOf(tok, theme)};`);
    for (const tok of t.shadow?.tokens ?? []) out.push(`  --${tok.name}: ${colorOf(tok, theme)};`);
    out.push('}');
  };
  block(':root, :root[data-theme="light"]', first);
  for (const theme of others) {
    // The OS setting picks the theme unless the page pins one with data-theme
    out.push(`@media (prefers-color-scheme: ${theme}) {`);
    block(`  :root:not([data-theme="light"])`, theme);
    out.push('}');
    block(`:root[data-theme="${theme}"]`, theme);
  }
  out.push(':root {');
  for (const fam of ['spacing', 'radius', 'size', 'timing']) for (const tok of t[fam]?.tokens ?? []) out.push(`  --${tok.name}: ${tok.value};`);
  for (const [name, stack] of Object.entries(t.type.families)) out.push(`  --font-${name}: ${stack};`);
  for (const g of t.type.groups)
    for (const st of g.styles) out.push(`  --text-${st.name}: ${st.fontWeight} ${st.fontSize}/${st.lineHeight} var(--font-${st.family || g.family});`);
  out.push('}');
  return out.join('\n') + '\n';
}

async function bundle() {
  const r = await build({
    entryPoints: [join(ds, 'src', 'index.jsx')],
    bundle: true,
    format: 'iife',
    jsxFactory: 'h',
    jsxFragment: 'Frag',
    target: 'es2020',
    write: false,
    legalComments: 'inline',
  });
  return r.outputFiles[0].text;
}

const files = [
  [join(ds, 'tokens.css'), tokensCss(JSON.parse(readFileSync(join(ds, 'tokens.json'), 'utf8')))],
  [join(ds, 'bundle.js'), await bundle()],
];
let stale = 0;
for (const [path, text] of files) {
  if (check) {
    let old = '';
    try { old = readFileSync(path, 'utf8'); } catch { /* missing counts as stale */ }
    if (old !== text) { console.error(`out of date: ${path} (run npm run build)`); stale++; }
  } else {
    writeFileSync(path, text);
    console.log(`wrote ${path}`);
  }
}
process.exit(stale ? 1 : 0);
